config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}
  resources :users, only: :destroy
  get 'welcome' => 'activities#edit'
  get 'dashboard' => 'activities#dashboard'
  resources :activities, only: [:update, :index]
  get 'history' => 'activities#index'
  root 'static_pages#home'
  get 'one' => 'static_pages#one'
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id         :integer          not null, primary key
#  start_time :datetime
#  end_time   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

include ActionView::Helpers::TextHelper
class Activity < ActiveRecord::Base
	belongs_to :user

	validate :end_time_cannot_be_in_future, on: :update
	validate :end_time_cannot_be_less_than_start_time, on: :update

	def total_time_spent_in_words
		s_time = Time.parse(start_time.to_s)
		e_time = Time.parse(end_time.to_s)
		total_spent = (e_time - s_time)
		hours = (total_spent/3600).to_i
		minutes = ((total_spent - (hours*3600))/60).to_i
		"#{pluralize(hours, 'hour') + ' and' if hours!=0} #{pluralize(minutes, 'minute')}"
	end

	def friendly_created_at
		created_at.strftime('%A, %d %B, %Y')
	end

	private

		def end_time_cannot_be_in_future
			if self.end_time != nil && self.end_time > DateTime.now.change(:offset => "+0000")
				errors.add(:end_time, "You cannot set a Check Out time in future")
				self.end_time = nil 
			end
		end
		
		def end_time_cannot_be_less_than_start_time
			if self.end_time != nil && self.start_time != nil && self.end_time < self.start_time
				errors.add(:end_time, "You cannot Check Out before you Check In: Come On! Be practical")
				self.end_time = nil
			end
		end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean          default("f")
#  name                   :string
#

class User < ActiveRecord::Base
	has_many :activities, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def todays_activity
  	activities.find_or_create_by(created_at: Date.today.to_datetime)
  end

  def get_authorized_activities(params = nil)
  	if try(:admin?) && params[:user_id] == nil
  		return Activity.where.not(user_id: self.id)
  	elsif try(:admin?) && params[:user_id] != nil
  		return Activity.where(user_id: params[:user_id])
  	else
  		return activities.limit(7)
  	end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	include ActivitiesHelper
	before_filter :authenticate_user
	before_filter :authenticate_admin, only: :dashboard
	before_action :set_todays_activity, except: :dashboard

	def index
		@activities = current_user.get_authorized_activities(user_id: params['user'])
		@user = User.find_by(id: params['user'])
	end

	def edit
	end

	def update
		@todays_activity = current_user.todays_activity
		@todays_activity.update(convert_to_24_hours(params_activity))
		respond_to do |format|
			format.html {redirect_to welcome_path}
			format.js
		end
	end

	def dashboard
		@users = User.where(admin: false)
	end

	private
		def params_activity
			params.require(:activity).permit(:start_time, :end_time)
		end

		def set_todays_activity
			@todays_activity = current_user.todays_activity
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # terenary operator doesn't work here - why?
    if resource.try(:admin?)
      return dashboard_path
    else
      return welcome_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  private
	  def redirect_to_activity_if_signed_in
  		redirect_to welcome_path if user_signed_in?
	  end

	  def authenticate_user
	  	redirect_to root_path unless signed_in?
	  end

    def authenticate_admin
      redirect_to root_path unless current_user.try(:admin?)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :redirect_to_activity_if_signed_in

	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
  	User.find(params['id']).destroy
  	redirect_to dashboard_path
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
	def convert_to_24_hours(params)
		if params['start_time']
			start_time = params['start_time']
			start_time.gsub!(/\A\d+/, (start_time.match(/\A\d+/)[0].to_i+12).to_s) if start_time.include?('PM')
			params['start_time'] = start_time
			return params
		elsif params['end_time']
			end_time = params['end_time']
			end_time.gsub!(/\A\d+/, (end_time.match(/\A\d+/)[0].to_i+12).to_s) if end_time.include?('PM')
			params['end_time'] = end_time
			return params
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_end_form.html.erb
<div class="time_form">

	<div class="quote-banner">
		<h3>At what time did you leave?</h3>
	</div>

	<% if @todays_activity.errors.any? %>
		<div class="row errors"><%= @todays_activity.errors[:end_time].join('') %></div>
	<% end %>

	<div class="row">
		<%= form_for(@todays_activity, html: {class: 'todays_time'}, remote: true) do |f| %>
			<%= f.text_field :end_time %>
			<%= f.submit "Check Out", class: 'checkout' %>
		<% end %>
	</div>

</div>

app/views/activities/_result.html.erb
<div class="quote-banner">
	<h3>You spent <%= @todays_activity.total_time_spent_in_words %> at work today</h3>
</div>

app/views/activities/_start_form.html.erb
<div class="time_form">
		
	<div class="quote-banner">
		<h3>At what time did you come today?</h3>
	</div>

	<% if @todays_activity.errors.any? %>
		<div class="row errors"><%= @todays_activity.errors[:start_time].join('') %></div>
	<% end %>

	<%= form_for(@todays_activity, html: {class: 'todays_time'}, remote: true) do |f| %>
		<%= f.text_field :start_time %>
		<div class="btn-group">
		<%= f.submit "Check In", class: 'checkin' %>
		</div>
	<% end %>

</div>

app/views/activities/dashboard.html.erb
<div class="activities_index">
	<%= render partial: 'shared/header' %>
	<% unless @users.blank? %>
		<table class='activities_history'>
			<h2>Here's the list of students</h2>
			<% index = 1 %>
			<th>S.No</th>
			<th>Name</th>
			<th>View Report</th>
			<th>Delete</th>
			<% @users.each do |user| %>
				<tr>
					<td><%= index %></td>
					<td><%= user.name %></td>
					<td><%= link_to "View Report", activities_path(user: user) %></td>
					<td><%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></td>
				</tr>
				<% index += 1 %>
			<% end %>
		</table>
	<% else %>
		<h3 class='no-students-quote'>Oops, seems like nobody has registered</h3>
	<% end %>
</div>

app/views/activities/edit.html.erb
<div class="edit-activity">
	<%= render partial: 'shared/header' %>
	<div class="activities">
		<h2><%= @todays_activity.created_at.strftime('%A, %d %B, %Y') %></h2>
		<% if @todays_activity.start_time == nil %>
			<%= render partial: 'activities/start_form' %>
		<% elsif @todays_activity.end_time == nil %>
			<%= render partial: 'activities/end_form' %>
		<% else %>
		  <%= render partial: 'activities/result' %>
		<% end %>
	</div>
</div>

app/views/activities/index.html.erb
<div class="activities_index">
	<%= render partial: 'shared/header' %>
	<% if current_user.try(:admin?) %>
		<h2>Here's <%= @user.name.gsub(/\s.*/, '') %>'s attendance report</h2>
	<% else %>
		<h2>Here's what you did last in the last 7 days</h2>
	<% end %>
	<table class='activities_history'>
		<tr>
			<th>S.No.</th>
			<th>Date</th>
			<th>Start Time</th>
			<th>End Time</th>
			<th>Total Time Spent</th>
		</tr>
	<% index = 1 %>
	<% @activities.each do |activity| %>
		<tr>
			<td><%= index %></td>
			<td><%= activity.created_at.strftime('%d %h %Y') %></td>
			<td><%= activity.start_time.strftime('%I:%M %p') if activity.start_time %></td>
			<td><%= activity.end_time.strftime('%I:%M %p') if activity.end_time %></td>
			<td><%= activity.total_time_spent_in_words if(activity.start_time && activity.end_time) %></td>
			<% index += 1 %>
		</tr>
	<% end %>
	</table>
</div>

app/views/activities/update.js.erb
<% if @todays_activity.start_time == nil %>
  $('.time_form').replaceWith("<%= escape_javascript(render partial: 'activities/start_form') %>");
  $('#activity_start_time, #activity_end_time').timepicker({
		'minTime': "07:00AM",
		'maxTime': '11:00PM',
		'scrollDefault': 'now',
		'forceRoundTime': true,
		'timeFormat': 'h:i:A',
		'step': 15
	});
	$('#activity_start_time, #activity_end_time').timepicker('setTime', new Date());
<% elsif @todays_activity.end_time == nil %>
  $('.time_form').replaceWith("<%= escape_javascript(render partial: 'activities/end_form') %>");
  $('#activity_start_time, #activity_end_time').timepicker({
		'minTime': "<%= escape_javascript(@todays_activity.start_time.to_s) %>",
		'maxTime': '11:00PM',
		'scrollDefault': 'now',
		'forceRoundTime': true,
		'timeFormat': 'h:i:A',
		'step': 15
	});
	$('#activity_start_time, #activity_end_time').timepicker('setTime', new Date());
<% else %>
  $('.time_form').replaceWith("<%= escape_javascript(render partial: 'activities/result') %>");
<% end %>

app/views/confirmable/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HourGlass</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.12/jquery.timepicker.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.6.12/jquery.timepicker.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Muli:300' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Arvo:400" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default shared-navbar">
  <div class="container container-main">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#right-collapse-section">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user.try(:admin?) %>
        <%= link_to 'HourGlass', dashboard_path, class: 'navbar-brand' %>
      <% else %>
        <%= link_to 'HourGlass', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="right-collapse-section">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user.try(:admin?) %>
            <%= link_to 'Dashboard', dashboard_path %>
          <% else %>
            <%= link_to 'History', history_path %>
          <% end %>
        </li>
        <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Logout&nbsp;&nbsp;<i class="fa fa-sign-out"></i></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/home.html.erb
<div class="static_pages_home">
	<div class="row">
		<div class="container">
			
		<div class="col-md-1"></div>
		<div class="col-md-10">
		  <h2><b>HourGlass</b><br />lets you track the time you spend at work</h2>
		  <div class="action-buttons">
		  	<%= link_to 'Login', new_user_session_path, class: 'button login-button' %>
		  	<%= link_to 'Get Started', new_user_registration_path, class: 'button signup-button' %>
		  </div>
		</div>
		<div class="col-md-1"></div>

		</div>
	</div>
</div>

app/views/static_pages/one.html.erb
<h2>One.html</h2>